import { ReactNode } from "react";
import Head from "next/head";
import { Flex } from "@chakra-ui/react";
import { Navbar } from "../Navbar";
import { useContext } from "react";
import { ContractContext } from "../../contexts/contract";
import { ethers } from "ethers";

interface IProps {
  children?: ReactNode;
}

export default function Layout({ children, ...props }: IProps) {
  const { setAccount, account } = useContext(ContractContext);

  const connectHandler = async () => {
    const accounts = await window.ethereum.request({
      method: "eth_requestAccounts",
    });
    const account = ethers.utils.getAddress(accounts[0]);
    setAccount(account);
  };
  return (
    <>
      <Head>
        <title>DAX Assets Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h="100%" w="100%" direction="column">
        <Navbar account={account} handler={connectHandler} />

        {children}
      </Flex>
    </>
  );
}
